version: "3.7"

services:
  flask:
    build: .
    container_name: srg-tr-searcher
    restart: always
    expose:
      - 5000
    ports:
      - 5000:5000
#    volumes:
#      - .:/usr/src/app

#  nginx:
#    build: ./nginx
#    container_name: nginx-flask
#    restart: always
#    ports:
#      - "80:80"

